### ISSUE TITLE
Obvious feature request: font size

### ISSUE THREAD

**Issue by shoopdawoop** [bartreardon/Dialog-public#3]
This is great, thank you for sharing it.

If I may suggest an enhancement and a few minor changes:

– an option for setting font sizes would be great

– imo the App belongs in /Applications/Utilities/ ..
– .. and be named "Dialog" ...
– .. and, if it's not too much to ask, please name the release files "Dialog-0.3.3.zip" to make an admins life just a little bit easier ;)

Again, thank you!

**Comment by bartreardon** [comment]
Fair requests.

I'm not making a pkg yet. Still undecided where it should go but given `/Applications/Utilities` is easily accessible and running Dialog by itself does nothing, I'm inclined to plonk it into `/Library/Application Support` or some other nondescript location instead. For the time being, you can unzip to wherever you would want to 🙂

**Comment by bartreardon** [comment]
How would the font size thing behave? As in you'd like larger font in the title, in the message, both?...or smaller?

One future feature I'm looking at is basic markdown support which could satisfy that need

**Comment by shoopdawoop** [comment]
I was thinking about a smaller font size for the message text in case someone needs to be bugged with a more detailed explanation. Markdown sure would be nice.

**Comment by bartreardon** [comment]
hmm - that's kind of the intent of the `--informationbutton` option though. You can already put a significant wall of text in there (around 80 words of lorem ipsum when displaying a logo and almost 100 if you use `--hideicon`). The more info button text can be modified as well to say whatever you want it to say if you need it to be more descriptive and can have an added action component to redirect the user to a URL. I'm also cognisant of having _too_ much text otherwise users will skip over detail.

For the time being I'm going to focus on some markdown type formatting options.
